### ISSUE TITLE
Cannot compile application_glfw.cpp

### ISSUE THREAD

**Issue by scygan** [Themaister/Granite#1]
Hello! 

I am tring to build using Visual Studio 2015 Update 3, however following happens:
>  application_glfw.cpp(52): error C2664: 'bool Vulkan::Context::init_loader(PFN_vkGetInstanceProcAddr)': cannot convert argument 1 from 'GLFWvkproc (__cdecl *)(VkInstance,const char *)' to 'PFN_vkGetInstanceProcAddr'

This is because call convention is incompatible here: seems GLFW is `__cdecl`, while Vulkan function pointers are `__stdcall`.

**Comment by Themaister** [comment]
Worked on MSVC 2017 for me, weird. Anyways, pushed fix to master.
