### ISSUE TITLE
How to build from source on MSYS2 MINGW64?

### ISSUE THREAD

**Issue by iahung** [Themaister/Granite#114]
cmake configuration done but when running ninja it failed with:

`ninja: error: 'third_party/shaderc/third_party/glslang/OGLCompilersDLL/libOGLCompiler.a', needed by 'compiler/libgranite-compiler.a', missing and no known rule to make it`

**Comment by Themaister** [comment]
Debug build in glslang is broken on MinGW (not my bug). Try Release.
