### ISSUE TITLE
Enabled Nvidia shader cache causes crash on some cards with driver version >= 535

### ISSUE THREAD

**Issue by bsdcode** [Themaister/Granite#133]
See preceding details:
https://github.com/ares-emulator/ares/issues/1547
https://github.com/Themaister/parallel-rdp/issues/62

The commit https://github.com/Themaister/Granite/commit/1faa4016a6e5fa951b20d6bd99b51b59399f9097 disables some workarounds for Nvidia cards with driver versions >= 535:

https://github.com/Themaister/Granite/blob/246dde752f204440eb00fdccd4f0663bce32c734/vulkan/device.cpp#L878-L883

This results in freezes and crashes for some reported configurations:
* ares, simple64
* GeForce GT 1030, GeForce GTX 1080 Ti
* driver version 550.54.14, 560.70
* Windows, FreeBSD

A discovered workaround is to disable the Nvidia shader cache.

At least on my side, I can confirm that the removal of `gpu_props.driverVersion < VK_VERSION_MAJOR(535)` fixes the issue for my configuration. Because I'm no expert in graphics programming I have no idea what is the right way to do about it in the general case for all users. Is the condition too restrictive?

**Comment by Themaister** [comment]
This has to be a driver bug. There is zero reason why disabling that extension should fix GPU crashes.

**Comment by bsdcode** [comment]
Seems to be fixed with your latest update.
