### ISSUE TITLE
latest version build issues on ubuntu 20

### ISSUE THREAD

**Issue by neshume** [Themaister/Granite#23]
-- Configuring Shaderc to avoid building tests.
-- asciidoctor was not found - no documentation will be generated
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  **Could NOT find PythonInterp: Found unsuitable version "2.7.18", but**
  required is at least "3" (found /usr/bin/python)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:391 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindPythonInterp.cmake:169 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  third_party/shaderc/cmake/setup_build.cmake:38 (find_package)
  third_party/shaderc/CMakeLists.txt:44 (include)

Of course python3 is installed.

cheers,

neshume

**Comment by Themaister** [comment]
Not my problem, but shaderc, use -DPYTHON_EXECUTABLE=$(which python3).
