### ISSUE TITLE
[Question] Pipeline prewarm

### ISSUE THREAD

**Issue by amerkoleci** [Themaister/Granite#48]
I'm opening issue as there are no discussions tab.

I was wondering how does the renderer behave with D3D11 like logic where you create pipeline before draw/dispatch? 

I saw you use fossilize to prewarm pipelines, in my engine I'm using VkPipelineCache, should I expect speed up?
How big would get the cache in real game for example?

Thanks in advance

**Comment by Themaister** [comment]
VkPipelineCache should be fine enough. The prewarm is better. Eventually I'll need to overhaul the shader / PSO system to more easily support shipping stuff without runtime compilation of any kind. The current scheme is heavily focused on local dev.
