### ISSUE TITLE
Missing assets..

### ISSUE THREAD

**Issue by oscarbg** [Themaister/Granite#6]
Hi,
just testing Granite for first time.. built on Linux..
clone repo and did git submodule update --init
but still lots of samples error about assets:
 ./pcf-test

```
[ERROR]: open(), error: No such file or directory
[ERROR]: OSFilesystem::open(): MMapFile failed to open file
[ERROR]: Failed to open file: assets://pipelines.json

[ERROR]: open(), error: No such file or directory
[ERROR]: OSFilesystem::open(): MMapFile failed to open file
[ERROR]: Failed to open file: assets://shader_cache.json
[ERROR]: Failed to load shader cache assets://shader_cache.json from disk. Skipping ...
```

etc..
also
./gltf-viewer
[ERROR]: open(), error: No such file or directory
[ERROR]: OSFilesystem::open(): MMapFile failed to open file
[ERROR]: Failed to open file: assets://scene.glb
[ERROR]: application_create() threw exception: Failed to load GLTF file.

where to obtain this assets?
thanks..

**Comment by Themaister** [comment]
That's expected output, it just complains that various on-disk caches don't exist (yet). For gltf-viewer you have to give it a glTF file or it picks the default one, which does not exist in the repo.
