### ISSUE TITLE
Question about ETC2/EAC modifiler table

### ISSUE THREAD

**Issue by farosis** [Themaister/Granite#67]
would you please answer my question why you use half the table defined by Vulkan spec for ETC2/EAC modifiler table? and I've notice there is no SIGNED EAC format support in you eac path, is it related?
https://www.khronos.org/registry/DataFormat/specs/1.3/dataformat.1.3.html#Table-etc2eac-modifiers

**Comment by Themaister** [comment]
The lower half can be reconstructed from upper half with:
```
    int msb = int((payload[bit_offset >> 5] >> (bit_offset & 31)) & 1);
    int mod = etc2_alpha_modifier_table[table][lsb_index] ^ (msb - 1);
```
There is no test for R11_SNORM decode, so I suppose I just didn't implement it.
