### ISSUE TITLE
Question: DescriptorPool Design

### ISSUE THREAD

**Issue by v4vendeta** [Themaister/Granite#84]
Hey Themaister, I recently read your blog in https://themaister.net/blog/2019/04/20/a-tour-of-granites-vulkan-backend-part-3/ about the descriptor set management in Granite. In the blog you talked about the driver implementation of descriptor pool.

> On certain GPUs, allocating descriptor sets is, or at least used to be very costly. The descriptor pools might not be implemented as true pools (sigh …), so every vkAllocateDescriptorSets would mean a global heap allocation, absolutely horrible for performance.

I would like to know if mainstream PC/console platforms use this mechanism, and I would appreciate it if you could provide some documents or implementation detail about that.

**Comment by Themaister** [comment]
> I would like to know if mainstream PC/console platforms use this mechanism

None, this was only relevant for certain mobile drivers in the early days.

**Comment by v4vendeta** [comment]
thanks
