### ISSUE TITLE
Image usage mismatch

### ISSUE THREAD

**Issue by avpdiver** [Themaister/Granite#86]
https://github.com/Themaister/Granite/blob/613ada85f7c28d1446096828917bd1782f4aca63/renderer/render_graph.cpp#L373

Perhaps VK_IMAGE_USAGE_TRANSFER_SRC_BIT should be used here instead of VK_IMAGE_USAGE_TRANSFER_DST_BIT.

**Comment by Themaister** [comment]
Fixed. Nice spot.
