### ISSUE TITLE
Can push constants be dropped from the texture decoders?

### ISSUE THREAD

**Issue by nanley** [Themaister/Granite#91]
It looks like push constants aren't needed in `assets/shaders/decode/*.comp`.

The two changes needed for this are:
1. Replacing `registers.resolution` with `imageSize(OutputImage)` in
```glsl
    if (any(greaterThanEqual(coord.xy, registers.resolution)))                                 
        return; 
```
2. Replacing `registers.error_color` with `DECODE_8BIT ? uvec4(0xff, 0, 0xff, 0xff) : uvec4(0xffff)` in
```glsl
    imageStore(OutputImage, coord, registers.error_color);
```

**Comment by Themaister** [comment]
> imageSize(OutputImage)

This is a bit slower, but it's a trivial difference.

Does this even fix anything, or is it random nitpicking?

**Comment by nanley** [comment]
>> imageSize(OutputImage)
>
> This is a bit slower, but it's a trivial difference.

Interesting. I guess that makes sense with it being a query. What do you think about removing the resolution check altogether? (Just relying on drivers handling the OOB case). It generally seems to be faster without the check on my system.

> Does removing push constants fix a particular problem?

Not really. I had assumed that removing them would both optimize and simplify the code. I see now that it's not so clear-cut.

I'm interested in this particular bit of code because I and another mesa developer are working on integrating the ASTC compute shader for some GL use-cases. Because push constants aren't available in those contexts, this change would help reduce the diff between Mesa and Granite. No worries if you decide to keep them though. I understand that projects can have differing goals.

**Comment by Themaister** [comment]
You could just make trivial changes like that locally though. I suspect the shader cannot be used 1:1 either way, since it's Vulkan GLSL and uses spec constants which aren't directly GL compatible either way.
